apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: conk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: conk
    app.kubernetes.io/part-of: byoc-app-chgr
  name: conk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: conk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: conk
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-ityp-tenant/byoc-app-chgr/conk@sha256:744c1f70bddd4101104626391e87f929332b0210d9bef7d32952d6f39e9d653a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
