apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: conk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: conk
    app.kubernetes.io/part-of: byoc-app-chgr
  name: conk
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: conk
status:
  loadBalancer: {}
