apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: conk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: conk
    app.kubernetes.io/part-of: byoc-app-chgr
  name: conk
spec:
  rules:
  - host: conk-byoc-ityp-tenant.apps.824f7e727733a2ebc9d3.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: conk
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
